language: node_js

node_js:
  - "7.0"
sudo: false

matrix:
  include:
    - language: java
      jdk: oraclejdk8      

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar && cp antlr-4.7.1-complete.jar /usr/local/lib/

    
install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
